### ISSUE TITLE
Responsive design glitches

### ISSUE THREAD

**Issue by alescode** [zeppelinos/website#4]
At ~984px wide, the blockquote isn't visible. 
![image](https://user-images.githubusercontent.com/202928/40849215-af4b99b6-6597-11e8-9f13-6b61cb40e3db.png)

At ~700px wide, the illustration is incomplete and shown in the background. The contrast is too poor to read the blockquote text. 
![image](https://user-images.githubusercontent.com/202928/40849365-26834632-6598-11e8-8dd1-8ab26feb326d.png)

**Comment by facuspagnuolo** [comment]
Considered fixed after last deploy
